### ISSUE TITLE
В printlnCube лучше выводить развёртку кубика

### ISSUE THREAD

**Issue by mglukhikh** [AlmirBur/CubeJava#11]
Что-то в таком духе:

```
                B B B
                B B B
                B B B
W W W   Y Y Y   R R R   G G G
W W W   Y Y Y   R R R   G G G
W W W   Y Y Y   R R R   G G G
                O O O
                O O O
                O O O
```

**Comment by mglukhikh** [comment]
При этом предполагается, что в центре развёртки -- фронтальная грань, по бокам от неё -- левая и правая, сбоку от левой грани -- задняя, расстановка квадратов соответствует рисунку. Сверху и снизу, соответственно -- верхняя и нижняя грани. Так пользователь сможет хоть как-то представить, как грани расположены относительно друг друга. Не забудьте, что стыки граней на развёртке обязаны соответствовать стыкам граней на кубике (т.е. не должно быть такого, что какая-то грань на развёртке вдруг оказалась повёрнутой на 90 градусов по сравнению с реальным положением в кубике).

**Comment by mglukhikh** [comment]
И для этой функции тоже стоит иметь тесты. Если быть точным -- следует перенести основную часть её логики в `toString()` и протестировать, что выдаёт `toString()`.

**Comment by mglukhikh** [comment]
Не вижу нигде сделанной развёртки, хотя тикет и закрыт

**Comment by AlmirBur** [comment]
Метод scan

чт, 3 мая 2018 г., 19:44 Mikhail Glukhikh <notifications@github.com>:

**Comment by mglukhikh** [comment]
А тест написать хотя бы один?

**Comment by AlmirBur** [comment]
Написал

чт, 3 мая 2018 г., 20:34 Mikhail Glukhikh <notifications@github.com>:
