### ISSUE TITLE
Используйте имена граней в public API

### ISSUE THREAD

**Issue by mglukhikh** [AlmirBur/CubeJava#3]
В частности, в rotateFace. Несколько странно, когда имена у граней есть, но public API всё равно использует их номера.

**Comment by mglukhikh** [comment]
При этом заметьте, что `getFace()` использует таки имена! Такое API является, как говорят, неконсистентным (одна часть API не соответствует другой), что сильно путает его пользователей.

**Comment by mglukhikh** [comment]
Не сделано

**Comment by AlmirBur** [comment]
Изменил api

чт, 3 мая 2018 г., 19:47 Mikhail Glukhikh <notifications@github.com>:

**Comment by mglukhikh** [comment]
Ок, ну в целом стало лучше, спасибо.
