### ISSUE TITLE
Нет возможности создать кубик в заданном состоянии

### ISSUE THREAD

**Issue by mglukhikh** [AlmirBur/CubeJava#8]

**Comment by mglukhikh** [comment]
Не сделано

**Comment by AlmirBur** [comment]
Добавил метод

чт, 3 мая 2018 г., 19:45 Mikhail Glukhikh <notifications@github.com>:

**Comment by mglukhikh** [comment]
1. И опять нет теста
2. Можно сделать существенно большее количество проверок на корректность заданного состояния.
3. Пожалуйста, пишите нормальные commit messages.

**Comment by AlmirBur** [comment]
Добавил проверку, написал тест

пт, 4 мая 2018 г., 10:58 Mikhail Glukhikh <notifications@github.com>:
