### ISSUE TITLE
Добавьте "случайные" тесты

### ISSUE THREAD

**Issue by mglukhikh** [AlmirBur/CubeJava#9]
Например:

- проверьте, что кубик в случайном положении после четырехкратного поворота кубика в одинаковом направлении возвращается в это же положение
- проверьте, что кубик в случайном положении после четырехкратного поворота одной грани в одном и том же направлении возвращается в это же положение

**Comment by mglukhikh** [comment]
Случайных тестов толком нет

**Comment by AlmirBur** [comment]
Добавил

чт, 3 мая 2018 г., 19:45 Mikhail Glukhikh <notifications@github.com>:
